In [41]:
from src.utils.metrics import accuracy

In [42]:
import torch

In [43]:
a = torch.randint(10, (10, 1))
b = torch.randint(10, (10,1))


In [44]:
a

tensor([[9],
        [1],
        [1],
        [9],
        [2],
        [5],
        [4],
        [7],
        [7],
        [9]])

In [45]:
b

tensor([[5],
        [7],
        [9],
        [5],
        [9],
        [6],
        [2],
        [4],
        [8],
        [9]])

In [46]:
corr = accuracy(a, b)
corr

0.0

In [47]:
correct = (a == b).sum().item()
correct


1

In [48]:
a ==b

tensor([[False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [ True]])